#!/bin/bash

container_id=$(docker ps | grep kafka-connect | awk '{print $1;}')
echo $container_id
docker exec -i $container_id kafka-console-consumer $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25} ${26} ${27} ${28} ${29}