#!/bin/bash

container_id=$(docker ps | grep cp-ksql-cli | awk '{print $1;}')
echo $container_id
winpty docker exec -it $container_id /bin/bash ksql $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25} ${26} ${27} ${28} ${29}